name: quiver-time
channels:
- conda-forge
- defaults
dependencies:
- python=3.5
- matplotlib
- numpy
- scikit-learn>=0.15.0
- scipy>=0.11
- six==1.10.0
- keras>=2.0.0
- pandas>=0.17.1
- tensorflow>=0.12.1
- ipython
- jupyter
- flask
- flask_cors
- gevent
- pillow
